sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - valgrind
    - cppcheck
before_install:
  # download riscv32 compiler
  - chmod +x ./tools/download-riscv32-gcc-gdrive.sh
  - ./tools/download-riscv32-gcc-gdrive.sh
  - tar xvzf riscv-gcc.tar.gz --strip-components 2
  - export PATH=$PWD/riscv-elf/gcc-8.1.0/bin:$PATH
  - export HFOS_ROOT=$PWD
  - echo $PWD
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
  - cd ./software/tests/matrix/get_column/
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
